version: "3"
services:
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        command: --init-file /data/application/init.sql
        restart: always
        volumes:
            - ./database/init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: restobar
            MYSQL_USER: mysql
            MYSQL_PASSWORD: secret
    backend:
        depends_on:
            - mysql
        hostname: bakend
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        ports:
            - "5000:5000"
        environment:
            - DB_USER=mysql
            - DB_HOST=mysql
            - DB_NAME=restobar
            - DB_PASSWORD=secret
            - DB_DIALECT=mysql
            - DB_PORT=3306
            - NODE_ENV=development
            - PORT=5000
            - JWT_SECRET=abc123
    frontend:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        links:
            - backend
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./frontend:/app
